### ISSUE TITLE
Digital display automatic differs from western display

### ISSUE THREAD

**Issue by hubgogo** [bkader/Skada-WoTLK#103] opened 2023-01-27 08:33 UTC
V **1.8.84-3**

Digital display automatic differs from western display

![2](https://user-images.githubusercontent.com/91697479/215042363-7245b35d-761b-4829-aa18-11c9c7d2cf0c.gif)

![2023-01-27_160618](https://user-images.githubusercontent.com/91697479/215038419-2445a206-e6ea-4e7f-9729-40d2be8feaed.png)

**Comment by hubgogo** [comment] 2023-01-29 14:21
\World of Warcraft 3.3.5a\Logs\taint.log        text document    pollute

![2023-01-29_221507](https://user-images.githubusercontent.com/91697479/215332346-d86684b3-9cc0-4e7a-8a54-936e27d4bacd.png)


1/29 20:26:05.587  An action was blocked because of taint from Skada - CancelLogout()
1/29 20:26:05.587      Interface\FrameXML\StaticPopup.lua:1506 OnHide()
1/29 20:26:05.587      Interface\FrameXML\StaticPopup.lua:3452 StaticPopup_OnHide()
1/29 20:26:05.587      StaticPopup1:OnHide()
1/29 20:26:05.587      StaticPopup1:Hide()
1/29 20:26:05.587      Interface\FrameXML\StaticPopup.lua:3286 StaticPopup_Hide()
1/29 20:26:05.587      Interface\FrameXML\UIParent.lua:578


default setting 

Only changed the following

![2023-01-29_221802](https://user-images.githubusercontent.com/91697479/215332525-50bd1337-7a31-4e2f-9e3a-77b6d9e352ea.png)


![2023-01-29_221846](https://user-images.githubusercontent.com/91697479/215332634-e12cd35f-239d-4eb0-9996-2553bf96250b.png)


Version：1.8.84-3

**Comment by bkader** [comment] 2023-01-29 16:57
@hubgogo I don't know what's the best East Asia display system, I only know it is different from Western Display. Sorry but, unless you have a better format to suggest, I am closing this issue as it's not an issue.
As for taint, please read more about it, it's 99-100% not caused by the addon reported, you will have to try with only Skada enabled then we'll see because **CancelLogout** isn't used in Skada (_unless it existed in a shared lib, in which case nothing to be done except finding the addon causing it)_.

**Closed by bkader** 2023-01-29 16:57 UTC

**Comment by hubgogo** [comment] 2023-01-30 04:48
![2](https://user-images.githubusercontent.com/91697479/215389098-787c469c-4a58-4ead-9459-d03dbac0db00.gif)

Pictured above is   

4.4k=4.4千  1k=1千=1000

skada 1.8.84-3   2.8k show 0.3千   should be 2.8 千  Same as Details
（see the first gif）

**Comment by bkader** [comment] 2023-01-30 14:31
I think it's because of a typo in `Skada\Core\Functions.lua:212` file. Try to edit the line like on the screenshot and tell me if it's because of it.

![image](https://user-images.githubusercontent.com/4732702/215505143-9f2522aa-ede2-4ee5-beac-f7879947f6cb.png)

**Comment by hubgogo** [comment] 2023-01-31 01:27
try to edit line 212
![2023-01-31_090054](https://user-images.githubusercontent.com/91697479/215635534-b858b321-94b8-433a-aaac-196dfd2f78dc.png)

The result is valid

![3](https://user-images.githubusercontent.com/91697479/215635600-18e72a1f-a3c6-4b2b-8478-37d7624b8c27.gif)


Only the second stain problem remains


I tried turning skada off and there was no smudge, weird.

**Comment by hubgogo** [comment] 2023-01-31 05:48
For testing, the number of addons is very small

![2023-01-31_134353](https://user-images.githubusercontent.com/91697479/215676183-f5df1ef7-89d0-4129-9dfa-a053174642ea.png)


Stain appeared again during the morning test
![2023-01-31_134644](https://user-images.githubusercontent.com/91697479/215676374-e27c5a5d-9368-4af9-b188-8dd832b5b9d6.png)


1/31 09:33:28.957  An action was blocked because of taint from Skada - CancelLogout()
1/31 09:33:28.957      Interface\FrameXML\StaticPopup.lua:1488 OnHide()
1/31 09:33:28.957      Interface\FrameXML\StaticPopup.lua:3452 StaticPopup_OnHide()
1/31 09:33:28.957      StaticPopup1:OnHide()
1/31 09:33:28.957      StaticPopup1:Hide()
1/31 09:33:28.957      Interface\FrameXML\StaticPopup.lua:3286 StaticPopup_Hide()
1/31 09:33:28.957      Interface\FrameXML\UIParent.lua:577

problem still unknown

With the skada off there is no stain very strange
